# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9796f774eb0d69f8ffed3c37ed41f1c62f84061ca97ab24effbdb7d3d869bf129c9c26142ab5ddb5776fc9065e9171d61722a72eec57dac9b71035bd67194d

test:
  secret_key_base: d9cf35a0b52a2f51cbc744bf19de27415599425df0b19882d9eef98356035f6de431d26bc1283bb99ba83f0249fdb7924af1d9f94443e48263daaef4becba1a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
